### ISSUE TITLE
Viridis already available

### ISSUE THREAD

**Issue by emiltb** [marcosci/cividis#1]
Nice work. I just want to point you in direction of the packages [viridis](https://github.com/cran/viridis) and [viridisLite](https://github.com/cran/viridisLite) which are already on CRAN. With the viridis package the color scale can be readily used with scale_fill_viridis() and scale_color_viridis(). See the vignette at https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html

How is this different?

**Comment by emiltb** [comment]
I just noticed that you do mention the Viridis package in your references - should have read that properly beforehand. I am still confused as to why we need this package though.

**Comment by marcosci** [comment]
no worries, is not on CRAN ;) it was just a dry run, to play around with the viridis package and look how we can use more CVD scales there.

if you want to use cividis in viridis, wait for a response there: 

https://github.com/sjmgarnier/viridisLite/pull/7
